apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit_test_app
  ports:
  - protocol: "TCP"
    port: 8020
    targetPort: 8501
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-test-app
spec:
  selector:
    matchLabels:
      app: streamlit_test_app
  replicas: 4
  template:
    metadata:
      labels:
        app: streamlit_test_app
    spec:
      containers:
      - name: streamlit-app-container
        image: k8s-streamlit:test
        imagePullPolicy: Never
        ports:
        - containerPort: 8501